#############################################################################
# Makefile for building: SimpleUI
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sat Aug 11 00:37:16 2012
# Project:  SimpleUI.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile SimpleUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Ifltk -Ixml -Iio -Igtk -Igtk/sGtkRenderers -Igtk/sGtkCallbacks -Ikde -Ikde/sKdeCallbacks -Imisc -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -L/usr/lib64 -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sXforms.c \
		fltk/sFltk.cxx \
		fltk/sFltkCallbacks.cxx \
		fltk/sFltkWidgets.cxx \
		fltk/SimpleUIFltk.cxx \
		gtk/sGtk.c \
		io/io.c \
		kde/main.cpp \
		kde/sKDE.cpp \
		misc/string_func.c \
		test_xforms/radiotest.cxx \
		test_xforms/test_example2.c \
		xml/sParseXforms.c \
		gtk/sGtkCallbacks/sGtkCallback_GetValues.c \
		gtk/sGtkCallbacks/sGtkCallback_HelperFunctions.c \
		gtk/sGtkCallbacks/sGtkCallbacks.c \
		gtk/sGtkRenderers/sGtkParseTree.c \
		gtk/sGtkRenderers/sGtkRenderer_Helper.c \
		kde/sKdeCallbacks/sKde_Cb.cpp moc_sKDE.cpp \
		qrc_sKde.cpp
OBJECTS       = sXforms.o \
		sFltk.o \
		sFltkCallbacks.o \
		sFltkWidgets.o \
		SimpleUIFltk.o \
		sGtk.o \
		io.o \
		main.o \
		sKDE.o \
		string_func.o \
		radiotest.o \
		test_example2.o \
		sParseXforms.o \
		sGtkCallback_GetValues.o \
		sGtkCallback_HelperFunctions.o \
		sGtkCallbacks.o \
		sGtkParseTree.o \
		sGtkRenderer_Helper.o \
		sKde_Cb.o \
		moc_sKDE.o \
		qrc_sKde.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		SimpleUI.pro
QMAKE_TARGET  = SimpleUI
DESTDIR       = 
TARGET        = SimpleUI

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_sKde.h ui_glade2.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SimpleUI.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -o Makefile SimpleUI.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile SimpleUI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SimpleUI1.0.0 || $(MKDIR) .tmp/SimpleUI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SimpleUI1.0.0/ && $(COPY_FILE) --parents simpleUI.h sXforms.h fltk/sFltk.h fltk/SimpleUIFltk.h gtk/sGtk.h io/io.h kde/sKDE.h misc/misc.h xml/sXml.h gtk/sGtkCallbacks/sGtkCallbacks.h gtk/sGtkRenderers/sGtkRenderer.h kde/sKdeCallbacks/sKde_Cb.h .tmp/SimpleUI1.0.0/ && $(COPY_FILE) --parents kde/sKde.qrc .tmp/SimpleUI1.0.0/ && $(COPY_FILE) --parents sXforms.c fltk/sFltk.cxx fltk/sFltkCallbacks.cxx fltk/sFltkWidgets.cxx fltk/SimpleUIFltk.cxx gtk/sGtk.c io/io.c kde/main.cpp kde/sKDE.cpp misc/string_func.c test_xforms/radiotest.cxx test_xforms/test_example2.c xml/sParseXforms.c gtk/sGtkCallbacks/sGtkCallback_GetValues.c gtk/sGtkCallbacks/sGtkCallback_HelperFunctions.c gtk/sGtkCallbacks/sGtkCallbacks.c gtk/sGtkRenderers/sGtkParseTree.c gtk/sGtkRenderers/sGtkRenderer_Helper.c kde/sKdeCallbacks/sKde_Cb.cpp .tmp/SimpleUI1.0.0/ && $(COPY_FILE) --parents kde/sKde.ui xforms/glade2.ui .tmp/SimpleUI1.0.0/ && (cd `dirname .tmp/SimpleUI1.0.0` && $(TAR) SimpleUI1.0.0.tar SimpleUI1.0.0 && $(COMPRESS) SimpleUI1.0.0.tar) && $(MOVE) `dirname .tmp/SimpleUI1.0.0`/SimpleUI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SimpleUI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_sKDE.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_sKDE.cpp
moc_sKDE.cpp: kde/sKdeCallbacks/sKde_Cb.h \
		kde/sKDE.h
	/usr/bin/moc $(DEFINES) $(INCPATH) kde/sKDE.h -o moc_sKDE.cpp

compiler_rcc_make_all: qrc_sKde.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_sKde.cpp
qrc_sKde.cpp: kde/sKde.qrc
	/usr/bin/rcc -name sKde kde/sKde.qrc -o qrc_sKde.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_sKde.h ui_glade2.h
compiler_uic_clean:
	-$(DEL_FILE) ui_sKde.h ui_glade2.h
ui_sKde.h: kde/sKde.ui
	/usr/bin/uic kde/sKde.ui -o ui_sKde.h

ui_glade2.h: xforms/glade2.ui
	/usr/bin/uic xforms/glade2.ui -o ui_glade2.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

sXforms.o: sXforms.c simpleUI.h \
		sXforms.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sXforms.o sXforms.c

sFltk.o: fltk/sFltk.cxx fltk/sFltk.h \
		sXforms.h \
		simpleUI.h \
		xml/sXml.h \
		io/io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sFltk.o fltk/sFltk.cxx

sFltkCallbacks.o: fltk/sFltkCallbacks.cxx fltk/sFltk.h \
		sXforms.h \
		simpleUI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sFltkCallbacks.o fltk/sFltkCallbacks.cxx

sFltkWidgets.o: fltk/sFltkWidgets.cxx fltk/sFltk.h \
		sXforms.h \
		simpleUI.h \
		xml/sXml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sFltkWidgets.o fltk/sFltkWidgets.cxx

SimpleUIFltk.o: fltk/SimpleUIFltk.cxx fltk/SimpleUIFltk.h \
		sXforms.h \
		xml/sXml.h \
		io/io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SimpleUIFltk.o fltk/SimpleUIFltk.cxx

sGtk.o: gtk/sGtk.c simpleUI.h \
		sXforms.h \
		xml/sXml.h \
		io/io.h \
		gtk/sGtk.h \
		gtk/sGtkRenderers/sGtkRenderer.h \
		gtk/sGtkCallbacks/sGtkCallbacks.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sGtk.o gtk/sGtk.c

io.o: io/io.c io/io.h \
		simpleUI.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o io.o io/io.c

main.o: kde/main.cpp kde/sKDE.h \
		kde/sKdeCallbacks/sKde_Cb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o kde/main.cpp

sKDE.o: kde/sKDE.cpp kde/sKDE.h \
		kde/sKdeCallbacks/sKde_Cb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sKDE.o kde/sKDE.cpp

string_func.o: misc/string_func.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o string_func.o misc/string_func.c

radiotest.o: test_xforms/radiotest.cxx 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radiotest.o test_xforms/radiotest.cxx

test_example2.o: test_xforms/test_example2.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o test_example2.o test_xforms/test_example2.c

sParseXforms.o: xml/sParseXforms.c xml/sXml.h \
		sXforms.h \
		simpleUI.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sParseXforms.o xml/sParseXforms.c

sGtkCallback_GetValues.o: gtk/sGtkCallbacks/sGtkCallback_GetValues.c gtk/sGtk.h \
		gtk/sGtkCallbacks/sGtkCallbacks.h \
		misc/misc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sGtkCallback_GetValues.o gtk/sGtkCallbacks/sGtkCallback_GetValues.c

sGtkCallback_HelperFunctions.o: gtk/sGtkCallbacks/sGtkCallback_HelperFunctions.c gtk/sGtk.h \
		gtk/sGtkCallbacks/sGtkCallbacks.h \
		misc/misc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sGtkCallback_HelperFunctions.o gtk/sGtkCallbacks/sGtkCallback_HelperFunctions.c

sGtkCallbacks.o: gtk/sGtkCallbacks/sGtkCallbacks.c gtk/sGtk.h \
		gtk/sGtkCallbacks/sGtkCallbacks.h \
		misc/misc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sGtkCallbacks.o gtk/sGtkCallbacks/sGtkCallbacks.c

sGtkParseTree.o: gtk/sGtkRenderers/sGtkParseTree.c gtk/sGtkRenderers/sGtkRenderer.h \
		gtk/sGtkCallbacks/sGtkCallbacks.h \
		simpleUI.h \
		sXforms.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sGtkParseTree.o gtk/sGtkRenderers/sGtkParseTree.c

sGtkRenderer_Helper.o: gtk/sGtkRenderers/sGtkRenderer_Helper.c gtk/sGtkRenderers/sGtkRenderer.h \
		gtk/sGtkCallbacks/sGtkCallbacks.h \
		simpleUI.h \
		sXforms.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sGtkRenderer_Helper.o gtk/sGtkRenderers/sGtkRenderer_Helper.c

sKde_Cb.o: kde/sKdeCallbacks/sKde_Cb.cpp misc/misc.h \
		kde/sKdeCallbacks/sKde_Cb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sKde_Cb.o kde/sKdeCallbacks/sKde_Cb.cpp

moc_sKDE.o: moc_sKDE.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sKDE.o moc_sKDE.cpp

qrc_sKde.o: qrc_sKde.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_sKde.o qrc_sKde.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

