######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 11 00:41:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . sKdeCallbacks
INCLUDEPATH += . sKdeCallbacks

# Input
HEADERS += sKDE.h sKdeCallbacks/sKde_Cb.h ../misc/misc.h
FORMS += sKde.ui
SOURCES += main.cpp sKDE.cpp sKdeCallbacks/sKde_Cb.cpp
RESOURCES += sKde.qrc
